---
- name: Configure Docker on deployment server
  hosts: [server]
  become: true
  tasks:
  - name: update
    command: sudo apt update

  - name: Install python and pip
    command: sudo install -y python-pip

  - name: Install Docker
    command: sudo apt-get install -y docker.io
    become: yes
    become_user: root

  - name: Start Docker Service
    command: sudo systemctl start docker
    become: yes
    become_user: root

  - name: Deploy and Run Image
    command: docker run -itd -p 8090:8085 vijayalakshmis/insureme:latest
